import { StyleSheet } from 'react-native';
import { T } from './global';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: T.bg,
  },
  scrollContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  circleContainer: {
    width: 300,
    height: 300,
    borderRadius: 150,
    borderWidth: 1,
    borderColor: T.border,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  playerDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.green,
  },
  gameInfo: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  roundTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 8,
    color: T.textSec,
    fontFamily: T.mono,
    letterSpacing: 2,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  infoText: {
    marginLeft: 4,
    fontSize: 13,
    color: T.textSec,
    fontFamily: T.mono,
  },
  bidAskContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 150,
    marginTop: 8,
  },
  bidAskText: {
    fontSize: 13,
    color: T.textPri,
    fontFamily: T.mono,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginVertical: 16,
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: T.textPri,
    fontFamily: T.mono,
  },
  buttonContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginVertical: 16,
  },
  actionButton: {
    backgroundColor: T.surface2,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
    margin: 4,
  },
  buttonText: {
    color: T.textPri,
    fontWeight: 'bold',
    fontSize: 12,
    fontFamily: T.mono,
    letterSpacing: 1,
  },
  contractCard: {
    width: '90%',
    backgroundColor: T.surface,
    borderRadius: 2,
    padding: 16,
    marginTop: 20,
    borderWidth: 1,
    borderColor: T.border,
  },
  contractTitle: {
    fontWeight: 'bold',
    fontSize: 11,
    marginBottom: 8,
    color: T.textSec,
    fontFamily: T.mono,
    letterSpacing: 2,
  },
  contractText: {
    fontSize: 14,
    color: T.textPri,
    fontFamily: T.mono,
  },
});
