import { StyleSheet } from 'react-native';

// ─── Design Tokens ───────────────────────────────────────────────────────────
export const T = {
  bg:          '#080808',
  surface:     '#111111',
  surface2:    '#1a1a1a',
  border:      '#2a2a2a',
  borderAcc:   '#333333',
  green:       '#00ff88',
  greenDim:    '#00cc6a',
  red:         '#ff3b5c',
  redDim:      '#cc2d48',
  amber:       '#f59e0b',
  cyan:        '#06b6d4',
  blue:        '#3b82f6',
  blueDim:     '#2563eb',
  textPri:     '#e8e8e8',
  textSec:     '#888888',
  textDim:     '#444444',
  mono:        'monospace' as const,
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: T.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: T.textPri,
  },
  gameList: {
    width: '90%',
    maxWidth: 800,
    alignSelf: 'center',
    marginVertical: 16,
  },
  placeholder: {
    fontStyle: 'italic',
    color: T.textDim,
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  button: {
    backgroundColor: T.surface2,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
  },
  buttonText: {
    color: T.textPri,
    fontSize: 14,
    fontFamily: T.mono,
    letterSpacing: 1,
  },
  nav: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 32,
  },
  navLink: {
    color: T.textSec,
    fontSize: 14,
  },
  modal: {
    position: 'absolute',
    top: '40%',
    left: '10%',
    right: '10%',
    padding: 16,
    backgroundColor: T.surface,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
  },
  closeButton: {
    marginTop: 8,
    color: T.red,
    textAlign: 'center',
  },
});

export const aboutStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    backgroundColor: T.bg,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: T.textPri,
    marginBottom: 16,
    textAlign: 'center',
    letterSpacing: 2,
  },
  description: {
    fontSize: 16,
    color: T.textSec,
    textAlign: 'center',
    marginBottom: 24,
    maxWidth: 600,
    lineHeight: 24,
  },
  linkButton: {
    backgroundColor: T.surface2,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 2,
    marginTop: 16,
    borderWidth: 1,
    borderColor: T.border,
  },
  linkText: {
    color: T.textPri,
    fontSize: 14,
    textAlign: 'center',
    letterSpacing: 1,
  },
});

export const crmStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    maxWidth: 420,
    backgroundColor: T.surface,
    padding: 24,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
    shadowColor: T.blue,
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 20,
    elevation: 10,
  },
  title: {
    fontSize: 14,
    fontWeight: 'bold',
    color: T.textPri,
    marginBottom: 20,
    textAlign: 'center',
    letterSpacing: 3,
    fontFamily: T.mono,
  },
  inputContainer: {
    marginBottom: 14,
  },
  label: {
    fontSize: 11,
    color: T.textSec,
    marginBottom: 6,
    letterSpacing: 1.5,
    fontFamily: T.mono,
  },
  input: {
    backgroundColor: T.surface2,
    color: T.textPri,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
    fontFamily: T.mono,
    fontSize: 14,
  },
  switchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: T.border,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 20,
    gap: 10,
  },
  cancelButton: {
    backgroundColor: 'transparent',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
  },
  submitButton: {
    backgroundColor: T.blue,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 2,
  },
  buttonText: {
    color: T.textPri,
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1.5,
    fontFamily: T.mono,
  },
  errorText: {
    color: T.red,
    fontSize: 11,
    marginTop: 4,
    fontFamily: T.mono,
  },
});

export const joinModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    maxWidth: 420,
    backgroundColor: T.surface,
    padding: 24,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
    shadowColor: T.green,
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 20,
    elevation: 10,
  },
  title: {
    fontSize: 14,
    fontWeight: 'bold',
    color: T.textPri,
    marginBottom: 20,
    textAlign: 'center',
    letterSpacing: 3,
    fontFamily: T.mono,
  },
  inputContainer: {
    marginBottom: 14,
  },
  label: {
    fontSize: 11,
    color: T.textSec,
    marginBottom: 6,
    letterSpacing: 1.5,
    fontFamily: T.mono,
  },
  input: {
    backgroundColor: T.surface2,
    color: T.textPri,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
    fontFamily: T.mono,
    fontSize: 14,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 20,
    gap: 10,
  },
  cancelButton: {
    backgroundColor: 'transparent',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
  },
  submitButton: {
    backgroundColor: T.green,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 2,
  },
  buttonText: {
    color: T.bg,
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1.5,
    fontFamily: T.mono,
  },
  errorText: {
    color: T.red,
    fontSize: 11,
    marginTop: 4,
    fontFamily: T.mono,
  },
});

export const gameListStyles = StyleSheet.create({
  container: {
    width: '100%',
    backgroundColor: 'transparent',
    paddingHorizontal: 4,
  },
  title: {
    fontSize: 11,
    fontWeight: 'bold',
    color: T.textSec,
    marginBottom: 10,
    letterSpacing: 2,
    fontFamily: T.mono,
  },
  list: {
    maxHeight: 300,
  },
  listContent: {
    gap: 4,
  },
  gameItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: T.surface2,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
    borderLeftWidth: 2,
    borderLeftColor: T.green,
  },
  gameDetails: {
    flex: 1,
  },
  gameName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: T.textPri,
    fontFamily: T.mono,
    letterSpacing: 0.5,
  },
  gameInfo: {
    fontSize: 11,
    color: T.textSec,
    marginTop: 2,
    fontFamily: T.mono,
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  joinButton: {
    backgroundColor: T.surface,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
  },
  joinButtonText: {
    color: T.textPri,
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: T.mono,
    letterSpacing: 1,
  },
  noGamesContainer: {
    alignItems: 'center',
    paddingVertical: 30,
  },
  noGamesText: {
    fontSize: 13,
    color: T.textDim,
    textAlign: 'center',
    fontFamily: T.mono,
  },
  loadingText: {
    textAlign: 'center',
    fontSize: 12,
    marginTop: 20,
    color: T.textDim,
    fontFamily: T.mono,
  },
  gameCode: {
    fontSize: 12,
    color: T.textDim,
    marginTop: 4,
    fontFamily: T.mono,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    maxWidth: 420,
    backgroundColor: T.surface,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
    padding: 24,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: T.textPri,
    marginBottom: 16,
    textAlign: 'center',
    letterSpacing: 3,
    fontFamily: T.mono,
  },
  gameListStyles: {
    fontSize: 12,
    color: T.textDim,
    marginBottom: 15,
    textAlign: 'center',
    fontFamily: T.mono,
  },
  input: {
    backgroundColor: T.surface2,
    color: T.textPri,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
    marginBottom: 10,
    fontFamily: T.mono,
    fontSize: 14,
  },
  cancelButton: {
    backgroundColor: 'transparent',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
  },
  submitButton: {
    backgroundColor: T.blue,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 2,
  },
  buttonText: {
    color: T.textPri,
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1,
    fontFamily: T.mono,
  },
  errorText: {
    color: T.red,
    fontSize: 11,
    marginTop: 4,
    fontFamily: T.mono,
  },
  refreshButton: {
    backgroundColor: T.surface2,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshButtonText: {
    color: T.textSec,
    fontWeight: 'bold',
    fontSize: 12,
    fontFamily: T.mono,
    letterSpacing: 1,
  },
  countdownText: {
    fontSize: 11,
    color: T.textDim,
    fontFamily: T.mono,
  },
});
